[tool.poetry]
name = "googledrive_cli"
version = "0.1.0"
description = ""
authors = ["DaniilMP3 <daniilpurisov390@gmail.com>"]
readme = "README.md"
packages = [{include = "googledrive_cli"}]

[tool.poetry.dependencies]
python = "^3.10"
pyjwt = "^2.8.0"
click = "^8.1.7"

[tool.poetry.scripts]
main = "googledrive_cli.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
